### PR TITLE
Unneccesary number concatination Title and Sentence casing.

### PR DESCRIPTION
**Pull request by ThaDrone**
# What it does:
It adds a field to the CamelOption struct: concat_num. If a number should be concatinated, this should be set to 'true'. In the if statement in the to_case_camel_like in the branch "is_numeric",  there is now a check for concat_num. 
- If concat_num is true, the branch will execute as normal, pushing the number to the string without a seperator. 
- If concat_num is not true, the branch will continue like it is a regular char, pushing the number to the string as a new word. 

# Why it does it:
Currently numbers are not handled correctly in title and sentence casing. The numbers are concatenated into the previous word. 

|input|case type|expected|actual|
|--|---|---|--|
|"foo 1 bar 2"| Title| "Foo 1 Bar 2"| "Foo1 Bar2"|
|"foo 1 bar 2"|Sentence|  "Foo1 bar 2"|"Foo 1 Bar 2"|

# Related issues:
https://github.com/whatisinternet/Inflector/issues/74

### CODE REVIEW

**Comment by dcormier** [comment]
This has been sitting here for a while, @chrislearn.

**Comment by ThaDrone** [comment]
@dcormier 

If you need to have the functionality I added, I would recommend forking my fork and use that as a dependency on your project. 

I see @chrislearn has some activity on his profile so he is still alive and might merge it some day :)

**Review by chrislearn — APPROVED** [review]

**Comment by omid** [comment]
The issues section is also OFF, so I report it here!

@chrislearn please have releases and mention the changes there, or at least fill the CHANGELOG.md file for users to understand the version changes easier.

The last report in CHANGELOG is for 0.11.x which I think is for the original project.

**Comment by chrislearn** [comment]
Changes can be found here:
https://github.com/chrislearn/cruet/releases

**Pull request merged**
